version: "3"
services:
  oradb:
    image: oracle/database:19.3.0-ee
    build:
      context: ./OracleDatabase/19.3.0
      args:
        DB_EDITION: ee
    environment:
      ORACLE_SID: db1930
      ORACLE_PDB: pdb1930
      ORACLE_PWD: oracle
    expose:
      - 1521
      - 5500
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - /u01/volumes/ora1930_oradata:/opt/oracle/oradata

  oas:
    image: oracle/oas:6.4.0
    build:
      context: ./OracleAnalyticsServer/6.4.0
    stop_grace_period: 600s
    environment:
        BI_CONFIG_RCU_DBSTRING: oradb:1521:pdb1930
        BI_CONFIG_RCU_PWD: oracle
    depends_on: [oradb]
    links:
      - oradb
    expose:
      - 9500-9514
    ports:
      - 9500-9514:9500-9514
#    volumes:
#      - ./oas59....

  rstudio:
    image: thedoc/rstudio:3.6.1
    build:
      context: ./Rstudio
    depends_on: [oradb]
    links:
      - oradb
    expose:
      - 8787
    ports:
      - 8787:8787

  jupyter:
    image: jupyter/datascience-notebook:latest
    expose:
      - 8888
    ports:
      - 8888:8888
    volumes:
      - $HOME/jupyter:/home/jovyan/work
