rollback;


drop table call_center_ext;
drop table catalog_page_ext;
drop table catalog_returns_ext;
drop table catalog_sales_ext;
drop table customer_ext;
drop table customer_address_ext;
drop table customer_demographics_ext;
drop table date_dim_ext;
drop table dbgen_version_ext;
drop table household_demographics_ext;
drop table income_band_ext;
drop table inventory_ext;
drop table item_ext;
drop table promotion_ext;
drop table reason_ext;
drop table ship_mode_ext;
drop table store_ext;
drop table store_returns_ext;
drop table store_sales_ext;
drop table time_dim_ext;
drop table warehouse_ext;
drop table web_page_ext;
drop table web_returns_ext;
drop table web_sales_ext;
drop table web_site_ext;

drop table call_center cascade constraints;
drop table catalog_page cascade constraints;
drop table catalog_returns cascade constraints;
drop table catalog_sales cascade constraints;
drop table customer cascade constraints;
drop table customer_address cascade constraints;
drop table customer_demographics cascade constraints;
drop table date_dim cascade constraints;
drop table dbgen_version cascade constraints;
drop table household_demographics cascade constraints;
drop table income_band cascade constraints;
drop table inventory cascade constraints;
drop table item cascade constraints;
drop table promotion cascade constraints;
drop table reason cascade constraints;
drop table ship_mode cascade constraints;
drop table store cascade constraints;
drop table store_returns cascade constraints;
drop table store_sales cascade constraints;
drop table time_dim cascade constraints;
drop table warehouse cascade constraints;
drop table web_page cascade constraints;
drop table web_returns cascade constraints;
drop table web_sales cascade constraints;
drop table web_site cascade constraints;